name: "Buildstep"
description: "Build ATT firmware"
inputs:
  memfault_release:
    type: boolean
    required: false
    default: false
  board:
    type: string
    required: true
  short_board:
    type: string
    required: true
  version:
    type: string
    required: false
    default: "0.0.0-dev"
  path:
    type: string
    required: true
    default: "."
  debug:
    type: boolean
    required: false
    default: false
  mqtt:
    type: boolean
    required: false
    default: false
  modem_trace:
    type: boolean
    required: false
    default: false
  push_memory_badges:
    type: boolean
    required: false
    default: false
  external_gnss:
    type: boolean
    required: false
    default: false
  buffer_flash:
    type: boolean
    required: false
    default: false
  buffer_ram:
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Build firmware
      working-directory: ${{ inputs.path }}
      shell: bash
      run: |
        params=()
        if [[ "${{ inputs.debug }}" == "true" ]]; then
          cat overlay-upload-modem-traces-to-memfault.conf >> overlay-debug-att.conf
          if [[ "${{ inputs.memfault_release }}" == "true" ]]; then
            echo CONFIG_MEMFAULT_NCS_FW_VERSION_STATIC=y >> overlay-debug-att.conf
          fi
          params+=("-DEXTRA_CONF_FILE=overlay-debug-att.conf")
          params+=("-DEXTRA_DTC_OVERLAY_FILE=overlay-upload-modem-traces-to-memfault.overlay")
        fi
        if [[ "${{ inputs.mqtt }}" == "true" ]]; then
          params+=("-DEXTRA_CONF_FILE=$(pwd)/../examples/modules/cloud/overlay-mqtt.conf")
        fi
        if [[ "${{ inputs.modem_trace }}" == "true" ]]; then
          params+=("-DEXTRA_CONF_FILE=overlay-modem-trace-over-uart.conf")
          params+=("-DEXTRA_DTC_OVERLAY_FILE=overlay-modem-trace-shmem.overlay")
        fi
        if [[ "${{ inputs.external_gnss }}" == "true" ]]; then
          echo "CONFIG_MODEM_ANTENNA_GNSS_EXTERNAL=y" > overlay-external-gnss.conf
          params+=("-DEXTRA_CONF_FILE=overlay-external-gnss.conf")
        fi
        if [[ "${{ inputs.buffer_flash }}" == "true" ]]; then
          params+=("-DCONFIG_APP_STORAGE_BACKEND_LITTLEFS=y")
          params+=("-DCONFIG_APP_STORAGE_LOG_LEVEL_DBG=y")
        fi
        if [[ "${{ inputs.buffer_ram }}" == "true" ]]; then
          params+=("-DCONFIG_APP_STORAGE_LOG_LEVEL_DBG=y")
        fi
        west build -b ${{ inputs.board }} \
            -d build \
            -p --sysbuild -- \
            ${params[@]} 2>&1 | tee ../../artifacts/build_output_${{ inputs.short_board }}.log

        if [[ "${{ inputs.short_board }}" == "thingy91x" ]]; then
          if [[ "${{ inputs.push_memory_badges }}" == "true" ]]; then
            west build -d build/app -t rom_report
            west build -d build/app -t ram_report
            cp build/app/rom.json ../../artifacts/rom_report_${{ inputs.short_board }}.json
            cp build/app/ram.json ../../artifacts/ram_report_${{ inputs.short_board }}.json
          fi
        fi

    - name: Copy artifacts
      shell: bash
      run: |
        cp ${{ inputs.path }}/build/merged.hex \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91.hex
        cp ${{ inputs.path }}/build/app/zephyr/.config \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91.config
        cp ${{ inputs.path }}/build/app/zephyr/zephyr.signed.bin \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91-update-signed.bin
        cp ${{ inputs.path }}/build/app/zephyr/zephyr.signed.hex \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91-update-signed.hex
        cp ${{ inputs.path }}/build/app/zephyr/zephyr.elf \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91.elf
        cp ${{ inputs.path }}/build/dfu_application.zip \
          artifacts/asset-tracker-template-${{ inputs.version }}-${{ inputs.short_board }}-nrf91-dfu.zip
