name: Create documentation bundle

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  create-ft-bundle:
    name: Create ft documentation bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create zip file
        run: |
          zip -r asset-tracker-template-ft.zip \
          docs/* mkdocs.yml

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v6
        with:
          name: asset-tracker-template-ft
          path: asset-tracker-template-ft.zip
          retention-days: 7
